### ISSUE TITLE
KV下の文章、行間つまってるように感じます...

### ISSUE THREAD

**Issue by hoshico** [tskaigi/tskaigi.github.io#30]
現状:
最初にくる文章としては詰まっているような〜

<img width="989" alt="スクリーンショット 2024-01-26 19 00 18" src="https://github.com/tskaigi/tskaigi.github.io/assets/77495217/dd0f0a61-855d-482f-bc4a-f51255dfac0d">

提案:
これくらいでも良いかも
<img width="1036" alt="スクリーンショット 2024-01-26 19 01 50" src="https://github.com/tskaigi/tskaigi.github.io/assets/77495217/9a84aec4-01d5-42f4-a4cd-5e23f4df348e">

**Comment by oku-44** [comment]
@hoshico 
そうですね！
leading-looseくらいで調整お願いできますでしょうか

**Comment by oku-44** [comment]
現在仮で上記スタイル当ててますが、行間が物足りなかったら随時変更してください!

**Comment by hoshico** [comment]
@oku-44 
あざます！
PCは変更していただいた感じで、スマホの方も少し調整加えました！PR出しております！
